name: "Commit Msg Check"
description: "Checks commit messages using a Python script"

inputs:
  base:
    description: "Base SHA for the commit range"
    required: false

  head:
    description: "Head SHA for the commit range"
    required: false

  body-char-limit:
    required: false
    default: "72"
    description: "Word wrap limit for each line in the body"

  sub-char-limit:
    required: false
    default: "50"
    description: "Character limit for subject"

  check-blank-line:
    required: false
    default: "true"
    description: "check for a blank line between commit title and body"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('${{ github.action_path }}/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Check commit messages
      shell: bash
      run: |
        python ${{ github.action_path }}/check_commits.py \
          --base "${{ inputs.base }}" \
          --head "${{ inputs.head }}" \
          --body-limit "${{ inputs.body-char-limit }}" \
          --sub-limit "${{ inputs.sub-char-limit }}" \
          --check-blank-line "${{ inputs.check-blank-line }}"
